language: node_js
node_js:
- '0.10'
script:
- grunt testCoveralls
addons:
  hosts:
  - login.localhost.in
  sauce_connect: true
env:
  global:
  - NODEJS_IP: 127.0.0.1
  - NODEJS_PORT: 8080
  - NODE_ENV: travis
  - FB_CALLBACK_URL: http://login.localhost.in:8080/auth/facebook/callback
  - TWITTER_CALLBACK_URL: http://login.localhost.in:8080/auth/twitter/callback
  - SESSION_SECRET: ilovetowriteanawesomeblog,
  - secure: hEcE3BSDRKaSYH0rNu7ZsF7nZHs+DXlfIAJpJGCOL6cFU3rfKpUgmXTZaGz8tuY/bZXTwN0miDfGtn+7T6gnV/3D4wxVXhBEXDUnWmCOhiDMHkPrmv2zJXiy5WbuPkjc8GCrvRnUrpfo1ETSiqhj5NSlfvWM6r8kQsvXdoYg1kE=
  - secure: Ye1t4smtC70vmsi57DBL2G6SyAHH9HpyWm3zCQWkRZpseWyidVTaP0qVw1SZ9gSGYdYKLPPcknGv43jq3pKGKXbWKoGkcFdBKHlLSitmbK2OH6JsdWkBV+JiUMjTROywfT9rJHzEWfZyms6C1CLZAfIIR99pduSA+wB5YIWr91Q=
  - secure: btysrd61OMR+wnEmtlsfHutlRylJy5VTtfXSriV4p6GBFElryIkPGa5Be/VN2z+TYJW9Gig3lXK67KLXnMkst6rQLhYR9ELPI/on8ZLEX+HTJUdYsIigUVFEmzsJ4/rNBiCB4NarcVQuhtoBS+S2f/qYXV5mUOxAwpEApMlZ1yw=
  - secure: X73x4mTCv+lm/+2qx4HObbhV58hvqs6vhDed/qbUTghPNHjMYtY7vgjHjgerMlXwzNl98wlVRjqO5+yB9Vv/yytfF8/NWUbAuKsFYXS9Wb5epiFT6N/KL2VSYmqTAnITwF26x157DllUF8Xa1kxgPEGe4Au6IyaaWtcCY+OFyyM=
  - secure: EDTBb6RCJwehXXSILapWbezkd5ZnZjXdQaUZ9/wymd+Taqpc31Hr950yaWmuCqmycBova8dmVd2sgOvP6PskeRD+jT4HoIUGL0EODNAnYC6DYzPXM8bNRAZJrMQoZFz0txGDtbl0e3qvx5qKQX7Cj3d7FTffTqvqihawBMwvDpc=
  - secure: RiDA0DhJ6XOywLjlB4PDODt+z3pTcm93Ephmzz1Y8n5I8fjgM7ZQL7PwgFk7p793i6ZYzRyWfBiV+FqpTQV/7jey06iuE61OyqEHNwElLVRXJKWB+kvAfMw7OtorEJ6US7NUo6RP+LlQaiYMqePjDbkZhQIRcT9bFGU0eSgBou0=
  - secure: C7KQPCYnPuYBaqQZvMtrABPliT1lvHyayQbsOZWC+5sKFx1UfaPHSSPOxaPN0gDjTvxhlzGaX1p4zSYLRuVFWEk8hpq1SEmu4W4K6etXlz9LQ2FH85MaicNns3wL2xAMJ0Ino1D412bnHr/tSTcAFo2bqcE7hcv4XQwQA3wWFUc=
  - secure: gEdToKDMrbTV44jBS0YD/BAs7A+oPIawiGgYt4trlHNT7QUw5cn9eDeiYl0x/XRoGyosTguvhMA0fOgwJQHP8ofBqE5nq0uunlM6zYQCLKz2hjN1TP9SIwztzde3NZadWs7jgamKFx9eyk4N7ASR02emYxr2nbQ4VJf5+T7BRUI=
  - secure: TqzrU4SYnYvhHp+PpDMyDovfBMLO1B6e2r56TCcCMheP3aR05MkfTltBLJn/cbxT6gPmvoc9qTh9k8Zr5FRt39YOR8JVhra4KKTkT5eFTYOLU3VjHCBtl/4e7dpHn8UpGZGhNYK2jgRt+sVLGeW3gK6SuNkvqcr+LbXxlJA+z40=
  - secure: ZfrPOkgIsZVgUbINkL4c6DlTO1Iqj0N1Xs+CKFDTZh0XzFDuojilEsguSGJkS9vmMpiSMTcEemYeSA4P2sRajRg4uM0ReDvA7zgCVMIhLeEFP5++m7Oud/kYmBD4tXuqVpv4Ts5FofAlw/HBc1x84cJkUnvN0UM6dIvE4PO4r7I=
  - secure: bF8AJfvfne+Eal2Y+ow4azi5Zn6lCCKo8X9GqWp4awLhdQCyguk2vX0qpVtwn34dcQlZNHUGn3HorJTJm0WJXMac6FEbpVKwW6hRE1TxAo0WyUoIDcxlpQOHBd7t+Hu5xnLLkpIyqFsYgtxEIyDNpYrH5+sWa0G/iosBf3LT2fo=
  - secure: RKCwauLdzpe0wV6TgClLBEU3N7lua7wnQLmgg9t8yLOSCT9akd9fJ0R9UmUf3MTsE+K2FgT2c6n4FqXcKp9Ht2X3Q8/QotOn76Ark15TS+oa2MnnkI3ga4v3qTFIKWfnN3psbW7lBWWpLR2HKti73QwWdxqyq38DEEwfhlviCPs=
  - secure: GVjc/AQSg6s9Xvhg2TRU/ELb5If8O/6vl8w3hS8sC93/GeAKFCsYZ3+0uf0ZAV7KQwy8E8RZarwXsWFyAhZ/4E9Cyqx37fXTqGgmJ+1S3Q9GA4mdPtcGOSkhMR5S1qOXzUJ2cy6dnAk+Q4BaPwAU50W83iXBxQiq2PtP28OStNo=
after_success:
- git fetch --unshallow
deploy:
- provider: heroku
  api_key:
    secure: Nw2oRN0sY/EeZ+lSzACmoWOIi+eAo2ZawLZZ/lSS9a9J1wT58VkQl+zmNlwoVF8HbxqqmWAn1142C4bsAUevT8koFt/yhRCCm0rbGnR7aIcbpWxRT+pn20DMqCibCYtRA1tCQ1ONYwmU44j+0eWbHoGZa/eurGenL0PMMITRktA=
  app: vast-chamber-5927
  on:
    repo: prasunsultania/demoblog
- provider: cloudcontrol
  email: prasun.sultania@gmail.com
  password:
    secure: gWS33jR889jTdOPo39xQ+TMXixjOXPkzofcG/VbNwn360+wQR9faDJJShxl6BtrsTdxzx8+IY430qXCQ/XBFK/AqjN+psMof7XpiOLgZyJtscW22E8y1/zZ8TwI1HoRVRcgY7s6n2GPVS/0wrmz5bHiBgCJhicjSmzVb0Ld824o=
  deployment: awesomeblog/default
  edge: true
  on:
    repo: prasunsultania/demoblog